sudo pip install alembic
sudo pip install amqp
sudo pip install anyjson
sudo pip install apns
sudo pip install apns-client
sudo pip install backports.ssl-match-hostname
sudo pip install billiard
sudo pip install boto
sudo pip install celery
sudo pip install celery-with-redis
sudo pip install certifi
sudo pip install cffi
sudo pip install chardet
sudo pip install cryptography
sudo pip install defusedxml
sudo pip install diff-match-patch
sudo pip install Django
sudo pip install django-auth-ldap
sudo pip install django-bitfield
sudo pip install django-classy-tags
sudo pip install django-cms
sudo pip install django-facebook
sudo pip install django-mptt
sudo pip install django-pipeline
sudo pip install django-redis-cache
sudo pip install django-redis-sessions
sudo pip install django-reversion
sudo pip install django-sekizai
sudo pip install django-w3c
sudo pip install docopt
sudo pip install enum34
sudo pip install Envelopes
sudo pip install et-xmlfile
sudo pip install facebook-sdk
sudo pip install fonttools
sudo pip install gcm-client
sudo pip install gitdb
sudo pip install GitPython
sudo pip install google-api-python-client
sudo pip install gunicorn
sudo pip install html2text
sudo pip install html5lib
sudo pip install httplib2
sudo pip install idna
sudo pip install ipaddress
sudo pip install jdcal
sudo pip install Jinja2
sudo pip install jwt
sudo pip install kombu
sudo pip install lxml
sudo pip install Mako
sudo pip install mandrill
sudo pip install Markdown
sudo pip install MarkupSafe
sudo pip install mock
sudo pip install module
sudo pip install nexmomessage
sudo pip install nodeenv
sudo pip install nodejs
sudo pip install oauth2client
sudo pip install oauthlib
sudo pip install openpyxl
sudo pip install optional-django
sudo pip install pika
sudo pip install Pillow
sudo pip install pip
sudo pip install poster
sudo pip install postmonkey
sudo pip install psycopg2
sudo pip install py-w3c
sudo pip install py4j
sudo pip install pyasn1
sudo pip install pyasn1-modules
sudo pip install pycparser
sudo pip install pycrypto
sudo pip install pydns
sudo pip install pyflakes
sudo pip install pygeoip
sudo pip install Pygments
sudo pip install pyOpenSSL
sudo pip install python-dateutil
sudo pip install python-ldap
sudo pip install python-ntlm
sudo pip install pytz
sudo pip install redis
sudo pip install requests
sudo pip install rsa
sudo pip install setproctitle
sudo pip install setuptools
sudo pip install simplejson
sudo pip install six
sudo pip install smmap
sudo pip install South
sudo pip install SQLAlchemy
sudo pip install stripe
sudo pip install suds
sudo pip install tornado
sudo pip install Twisted
sudo pip install uritemplate
sudo pip install wheel
sudo pip install xmlrunner
sudo pip install zope.interface
